version: "3.9"

services:
  litestar_crud:
    env_file: [.env]
    command: poetry run litestar database upgrade --no-prompt
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "litestar_crud"
    depends_on:
      - database
    ports:
      - "8080:8080"


  database:
    image: postgres:latest
    container_name: "postgres_litestar_crud"
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${database}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: